#!/usr/bin/env swift

import Foundation

struct Constant {
    let path: [String]
    let name: String
    let value: String
}

let fileManager = FileManager.default
let rootURL = URL(fileURLWithPath: fileManager.currentDirectoryPath)
let arguments = Array(CommandLine.arguments.dropFirst())
let checkOnly = arguments.contains("--check")
let paths = arguments.filter { $0 != "--check" }
let inputURL = paths.first.map { URL(fileURLWithPath: $0) }
    ?? rootURL.appendingPathComponent("PrivateStrings/ObfuscatedStrings.swift")
let outputURL = paths.dropFirst().first.map { URL(fileURLWithPath: $0) }
    ?? rootURL.appendingPathComponent("Sources/BaseView/Generated/ObfuscatedKeys.swift")

let source = try String(contentsOf: inputURL, encoding: .utf8)
let enumPattern = try NSRegularExpression(pattern: #"^\s*enum\s+([A-Za-z_][A-Za-z0-9_]*)\s*\{\s*$"#)
let constantPattern = try NSRegularExpression(pattern: #"^\s*static\s+let\s+([A-Za-z_][A-Za-z0-9_]*)\s*=\s*"([^"]*)"\s*$"#)

var stack: [String] = []
var constants: [Constant] = []

for rawLine in source.split(separator: "\n", omittingEmptySubsequences: false) {
    let line = String(rawLine)
    let trimmedLine = line.trimmingCharacters(in: .whitespaces)
    let range = NSRange(line.startIndex..<line.endIndex, in: line)

    if let match = enumPattern.firstMatch(in: line, range: range),
       let nameRange = Range(match.range(at: 1), in: line) {
        stack.append(String(line[nameRange]))
        continue
    }

    if let match = constantPattern.firstMatch(in: line, range: range),
       let nameRange = Range(match.range(at: 1), in: line),
       let valueRange = Range(match.range(at: 2), in: line) {
        guard stack.count >= 2 else {
            fatalError("Constants must be nested under ObfuscatedStringSource and a feature enum: \(line)")
        }
        constants.append(
            Constant(
                path: Array(stack.dropFirst()),
                name: String(line[nameRange]),
                value: String(line[valueRange])
            )
        )
        continue
    }

    if trimmedLine == "}" {
        guard !stack.isEmpty else {
            fatalError("Unexpected closing brace")
        }
        stack.removeLast()
        continue
    }

    if !trimmedLine.isEmpty && !trimmedLine.hasPrefix("//") {
        fatalError("Unsupported line in \(inputURL.path): \(line)")
    }
}

guard stack.isEmpty else {
    fatalError("Unclosed enum path: \(stack.joined(separator: "."))")
}

func mask(key: UInt8, index: Int) -> UInt8 {
    key &+ UInt8(truncatingIfNeeded: index &* 31) &+ 0xA5
}

func stableKey(for constant: Constant) -> UInt8 {
    var hash: UInt64 = 14_695_981_039_346_656_037
    let seed = (constant.path + [constant.name, constant.value]).joined(separator: ".")
    for byte in seed.utf8 {
        hash ^= UInt64(byte)
        hash &*= 1_099_511_628_211
    }
    return UInt8(truncatingIfNeeded: hash) | 1
}

func encodedBytes(for value: String, key: UInt8) -> [UInt8] {
    value.utf8.enumerated().map { index, byte in
        byte ^ mask(key: key, index: index)
    }
}

let grouped = Dictionary(grouping: constants) { $0.path }
let sortedPaths = grouped.keys.sorted { $0.joined(separator: ".") < $1.joined(separator: ".") }
var output = """
// Generated by scripts/generate-obfuscated-strings.swift from PrivateStrings/ObfuscatedStrings.swift.
// Source constants intentionally live outside Sources/BaseView so their plain text is not compiled into the library.

enum BaseViewObfuscatedKeys {

"""

for path in sortedPaths {
    let indent = "    "
    output += "\(indent)enum \(path.joined(separator: "_")) {\n"
    for constant in (grouped[path] ?? []).sorted(by: { $0.name < $1.name }) {
        let key = stableKey(for: constant)
        let byteList = encodedBytes(for: constant.value, key: key)
            .map(String.init)
            .joined(separator: ", ")
        let keyLiteral = String(format: "0x%02X", key)
        output += "\(indent)    static let \(constant.name) = ObfuscatedString.decode([\(byteList)], key: \(keyLiteral))\n"
    }
    output += "\(indent)}\n\n"
}

output += "}\n"

if checkOnly {
    let existing = try String(contentsOf: outputURL, encoding: .utf8)
    guard existing == output else {
        fatalError("\(outputURL.path) is out of date. Run: swift scripts/generate-obfuscated-strings.swift")
    }
} else {
    try fileManager.createDirectory(
        at: outputURL.deletingLastPathComponent(),
        withIntermediateDirectories: true
    )
    try output.write(to: outputURL, atomically: true, encoding: .utf8)
}
